apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vk.fullname" . }}
{{ include "vk.labels" . | indent 2 }}
type: Opaque
data:
  config.toml: {{ include "config" . | b64enc }}
  remote.yaml: {{ include "remotekubeconfig" . | b64enc }}